// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPcwZasSENl3Rj4R9qenQsuhnLQihWtu4',
    appId: '1:835761615634:web:bb7e4734eef167bdd379cb',
    messagingSenderId: '835761615634',
    projectId: 'erickshawshop-eb247',
    authDomain: 'erickshawshop-eb247.firebaseapp.com',
    storageBucket: 'erickshawshop-eb247.firebasestorage.app',
    measurementId: 'G-77VDHMV79E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUyqF9xexti-LwyUsFfb4VqGAJzj1a0fA',
    appId: '1:835761615634:android:ee5b8155f0f3d12dd379cb',
    messagingSenderId: '835761615634',
    projectId: 'erickshawshop-eb247',
    storageBucket: 'erickshawshop-eb247.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzMHOBqlUWK2MkbaO_MAvwiAVKUHuUSes',
    appId: '1:835761615634:ios:e27c1076dc933817d379cb',
    messagingSenderId: '835761615634',
    projectId: 'erickshawshop-eb247',
    storageBucket: 'erickshawshop-eb247.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzMHOBqlUWK2MkbaO_MAvwiAVKUHuUSes',
    appId: '1:835761615634:ios:e27c1076dc933817d379cb',
    messagingSenderId: '835761615634',
    projectId: 'erickshawshop-eb247',
    storageBucket: 'erickshawshop-eb247.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPcwZasSENl3Rj4R9qenQsuhnLQihWtu4',
    appId: '1:835761615634:web:11cd52bd29269a80d379cb',
    messagingSenderId: '835761615634',
    projectId: 'erickshawshop-eb247',
    authDomain: 'erickshawshop-eb247.firebaseapp.com',
    storageBucket: 'erickshawshop-eb247.firebasestorage.app',
    measurementId: 'G-8CP2TXRNP4',
  );
}
